AllCops:
  TargetRubyVersion: 2.5
inherit_from:
- .rubocop.relaxed.yml
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Metrics/BlockLength:
  Max: 50
Style/Attr:
  Exclude:
    - lib/webdrone/xpath.rb
Lint/DuplicateMethods:
  Exclude:
    - lib/webdrone/xpath.rb
